version: "3.9"

services:
  app:
    build: .
    container_name: infra_app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - prometheus
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=infra_monitor
      - DB_USER=monitor
      - DB_PASSWORD=monitor123
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: infra_db
    restart: always
    environment:
      POSTGRES_DB: infra_monitor
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: infra_prom
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: infra_grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  db_data:
